### ISSUE TITLE
[3.1.0.3] "Closed loop" button disappears after being on Open loop

### ISSUE THREAD

**Issue by nlof** [nightscout/AndroidAPS#2003] opened 2022-08-10 16:11 UTC
When trying to close loop (Omnipod) after being on open loop temporarily, the "closed loop" button disappears from the menu. I need to switch to "low BG suspend" first and only after that does "closed loop' button show up. 
Sequential screenshots as well as log attached. It occured multiple times, the last @ 19:09 in the logs.

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/9302061/AndroidAPS.log)

![Screenshot_2022-08-10-17-14-17-84](https://user-images.githubusercontent.com/70835405/183960763-879a77da-4bd8-43d8-935e-f829bed4e305.jpg)
![Screenshot_2022-08-10-17-14-31-62](https://user-images.githubusercontent.com/70835405/183960772-f6be305f-8a86-4d4a-9736-67d078ff0d2b.jpg)

**Comment by happygirlnyc70** [comment] 2022-08-17 10:03
I can confirm this behavior for both dev and master version. I can attach logs the next time it happens.

**Comment by Andries-Smit** [comment] 2022-08-17 14:45
Its a bug, 
You can only close the loop if objective 6 is completed.
https://github.com/nightscout/AndroidAPS/blob/master/app/src/main/java/info/nightscout/androidaps/dialogs/LoopDialog.kt#L156
To complete objective 6 you have to close it...
https://github.com/nightscout/AndroidAPS/blob/master/app/src/main/java/info/nightscout/androidaps/plugins/constraints/objectives/objectives/Objective6.kt#L21
Caused by commit https://github.com/nightscout/AndroidAPS/commit/c211c2e4c3abf1b71557751e58b02088cbe062e1
@MilosKozak what is there alternative, to prevent deadlock and keep the function?

**Comment by happygirlnyc70** [comment] 2022-08-17 15:18
To be clear, you are saying this is a bug. I have completed all of the objectives.

**Closed** 2022-08-18 11:45 UTC
