### ISSUE TITLE
[All lasts Dev's] AAPS entrys are deleted  in NightScout next morning

### ISSUE THREAD

**Issue by Alamo04** [nightscout/AndroidAPS#456] opened 2021-04-02 09:01 UTC
My system:
AAPS latest Dev, Pixel 5 Phone, Medtronic 754, OrangeLink.

Time of issue: Since a month, or longer, with different Dev versions.

Issue:
Canula-, Reservoir-, Battery- and Sensorchange, all of them are entered in AAPS from hand, or over pump history.
AAPS load this changes up to NightScout and everything is fine.
Next morning, all this changes are disappeared in NightScout and the old values are shown. This doesn't happen in AAPS.

I have to enter all this changes from hand into NightScout, or have to do it with AAPS again, with using date and time of the changes from the day before, then they lasts in Nightscout.

Can't attache log file, because my tablet and Smartphone doesn't download zip files.
So I mailed one to Andy Rozman. Perhaps I can attach it later with my pc.

PS: 
I wonder that it seems, that I'm alone with this issue, because there is no open one.
My Database at Atlas is pretty empty, so this is not the case.

**Comment by swissalpine** [comment] 2021-04-03 18:15
No, I can confirm this issue.

**Comment by andyrozman** [comment] 2021-04-04 00:09
A lot of data is not stored into Nightscout... While you can go into stats and see pump history, not everything in pump history is stored in Nightscout.... Most of items are only in App history (not even in app database) and are reloaded when you start AAPS next. What we store is: Boluses, TBRs, Cannula change and Insulin.Reservoir change. Everything else is ignored. On every start we read history for 36 hours (so we usually read 1-3 history pages), and that history is cleaned every hours, so you can see only 36 hours of history... That is when you go into RL Stats window and use the last tab...

**Comment by Alamo04** [comment] 2021-04-04 09:18
@andyrozman 
Thats ok, but Canula- and Reservoir change are deleted in Nightscout after a few hours, also batterie.- and sensor change.
In the past, AAPS stored this information in Nightscout and everything was fine. 

Since a month, or longer this entry's are deleted over night.

I change my Sensor-, Canula- and Reservoir normally at evening, Batterie every 14+ days over the day after she was died. 
All of this changes are shown correct in Nightscout, over the hole day and are deleted next day.

And that has nothing to do with history read, this happens also if I use the action Tab for batterie- and Sensor change.
So it has nothing to do with history readings, or pump driver.

That's a core AAPS issue.

**Comment by andyrozman** [comment] 2021-04-04 11:49
OK. Since first pump mentioned was Medtronic, I though this was MDT problem, but yes you are right, most of this event are not triggered from pump... So it can't be my fault... 
Guys are still changing database AND nightscout client, so that might have to do something with that... Dev shouldn't be used for looping, until its stable and released.

**Comment by Alamo04** [comment] 2021-04-04 13:03
I know that Dev versions are not stable and can have multiple issues.

I have 4 Medtronic pumps and 3 old and one new phones. 2 NightScout sites.
I use one phone for looping and one for testing 24/7.

The testing system is only for finding issues in dev versions and report them, but perhaps you are right and it is not helpful to do so.

I will stop testing dev versions and will do that only for Release Candidates and Master in the future.

**Comment by swissalpine** [comment] 2021-04-04 13:09
Here you can clearly see: In the past, data was saved, now it is not.
By the way: If nobody tests dev, not all bugs will be found. ;-)
![grafik](https://user-images.githubusercontent.com/12517693/113509679-40653500-9557-11eb-918d-a70fb5d58ea7.png)
![Screenshot_20210404-150521](https://user-images.githubusercontent.com/12517693/113509705-67236b80-9557-11eb-9288-25afda33f0d4.png)

**Comment by swissalpine** [comment] 2021-04-12 13:12
Canula age and Insulin age seems to work now ... - without any changes.

![grafik](https://user-images.githubusercontent.com/12517693/114399651-716de700-9ba1-11eb-89f8-1cdea23665e1.png)

**Comment by Alamo04** [comment] 2021-04-12 19:21
@swissalpine 
I enter all this data now in AAPS first and then also in NightScout, to be sure that they don't be deleted.
Will test it again with next Dev, but I'm still not sure if that is a bug. Perhaps it is intend ?

Don't know what to do, should I close this issue, because it is a dev version. Let Milos take this choise.

@MilosKozak
feel free to close this issue, if it is not helpful, or the work in progress is the reason.

**Comment by MilosKozak** [comment] 2021-06-23 20:34
hopefully fixed by https://github.com/nightscout/AndroidAPS/commit/a70f24a68aca5d98300c6e622e7732a3b833e426

**Closed by MilosKozak** 2021-06-23 20:34 UTC
