### ISSUE TITLE
[3.1.0.3-dev-g] [ComboV2] User Entry Log

### ISSUE THREAD

**Issue by markvader** [nightscout/AndroidAPS#2382] opened 2023-01-31 00:48 UTC
ComboV2 driver automatically recognises insulin cartridge change && (if newLevel > currentLevel)

Entry automatically made in the Careportal log and User entry log recording the change.

**The Careportal log entry shows** 
1. the time "hh:mm"
2. the title "Insulin Cartridge Change"
3. a note that the "Insulin reservoir change inserted automatically by combov2 driver".

All okay here

**The User Entry log shows** 
1. the time "hh:mm:ss"
2. the title "CAREPORTAL"
3. The combo icon
4. the date and time MM-DD-YY HH:MI:SS and the title "Insulin Cartridge Change"
5. the note "Insulin reservoir change inserted automatically by combov2 driver" is right aligned to the same width as the combo icon

**Issues:** 
1. the date time duplication.  In the entry I have their is a 1 second difference between the two entries, is this why it appears twice.  Does their need to be an increase in tolerance for timedelta between phone and pump?
2. The title on 3.1.0.3 for combov1 is 'Reservoir Change' rather than CAREPORTAL
3. Will removing the date time duplication give enough space to the note.

I can see that pumps like the DanaRS to not use the note parameter in its pumpSync.insertTherapyEventIfNewWithTimestamp record, however I see it's value in careportal, particularly as users switch over from old combo to new.

![careportal   user entry](https://user-images.githubusercontent.com/217953/215629826-34c2a872-6b53-4852-ac5e-6e8b55bfbce0.jpg)

@dv1

**Comment by dv1** [comment] 2023-01-31 08:26
> The title on 3.1.0.3 for combov1 is 'Reservoir Change' rather than CAREPORTAL

I am confused. Where does the combov1 (I assume you mean the old Ruffy based driver) use this? It does not enter any treatment.

**Comment by markvader** [comment] 2023-01-31 09:53
agreed, the ruffy driver is all user entry. 
![combo-careportal](https://user-images.githubusercontent.com/217953/215717980-45b78e88-72a4-464a-874a-ff373c266363.jpg)

I got someone to send me the danaRS screens, which has automatic cartridge change recognition (time: 22.21).  This user has also manually recorded the change (time: 22.24) (hence two different entries)
![danaRS](https://user-images.githubusercontent.com/217953/215725620-7d1b3c39-eb39-4582-921f-5839d0a02517.jpg)

**Comment by dv1** [comment] 2023-02-25 16:09
Can you try to cherry-pick https://github.com/dv1/AndroidAPS/commit/1ff34633d07b4a8205d7591b9bae142884c19319 and see if this fixes the issue for you?

**Comment by markvader** [comment] 2023-02-28 23:07
![Screenshot_2023-02-26-22-14-08-14_3eaa31bb2c2a38a1c605d9dc918cf694 (1)](https://user-images.githubusercontent.com/217953/222002715-0c9236f6-9881-49c2-b2a6-a59461a1bc5d.jpg)

The user entry for the automatic cartridge change remains the same with the long message squeezed to the right side of the screen.

**Comment by dv1** [comment] 2023-03-29 06:58
@markvader Can you confirm that the issue is fixed now in latest dev?

**Closed** 2023-04-05 15:50 UTC
