### ISSUE TITLE
Apps not responding while BG is changing. Had to press run now 

### ISSUE THREAD

**Issue by margogoodfellow** [nightscout/AndroidAPS#667] opened 2021-09-08 19:04 UTC
APPS did not respond for 20 min i had to press run now manually so it started working again. It worked fine for a few hours and it happened again. As you can see on the screenshot. Link to the logs attached. It happened at 14:30

https://drive.google.com/file/d/1wBriyCAbvbIbWKALabfkXQ_mdjoirgz2/view?usp=drivesdk

![Screenshot_20210908_195906_com google android apps docs](https://user-images.githubusercontent.com/68740119/132569177-1064937e-ad7b-4c68-9760-91f9d0c8f05e.jpg)
![Screenshot_20210908_200244](https://user-images.githubusercontent.com/68740119/132569443-ba04a314-c57a-443c-86da-5be500df84fd.jpg)

**Comment by MilosKozak** [comment] 2021-09-13 17:33
log doesn't contain timeframe with issue
TURN OFF AUTOSENS logging. it's huge and it's causing fast log rotation

**Comment by margogoodfellow** [comment] 2021-09-13 18:58
How do i turn it off please ? As I must be doing something wrong

**Comment by MilosKozak** [comment] 2021-09-14 18:56
Maintenance - Logging

**Comment by margogoodfellow** [comment] 2021-09-14 20:25
Thank you. I have done that now. I will have to wait when this happens
again to generate logs as i have deleted aps and reinstalled it and it
helped.

**Comment by savek-cc** [comment] 2021-10-15 18:38
@MilosKozak duplicate of https://github.com/nightscout/AndroidAPS/issues/598

**Comment by margogoodfellow** [comment] 2021-10-15 19:03
Nope the phone was charged and I have this option off. I use this phone for looping only . I had to delete the app and install it again and only this solved the problem.  I didn't have an issue since then but it wasn't first time when this happened   I have finally switch autosense and if it will occur again I will generate the logs

**Closed** 2021-11-10 15:23 UTC
Labels: question - more info needed

**Comment by margogoodfellow** [comment] 2021-12-01 20:50
https://drive.google.com/file/d/1r8zsKZe--5ifwzjb2SszRsNqc6ggyxH-/view?usp=drivesdk

Just had 15 min of loop not responding
