### ISSUE TITLE
Since Update 2.8.1.1 history is empty

### ISSUE THREAD

**Issue by FreDiabetics** [nightscout/AndroidAPS#227] opened 2021-01-12 19:53 UTC
Like the title says, since update to 2.8.1.1 the history  is totally empty. Doesn't matter how date I select nothings gets loaded. 

I'm using a different aaps version, but my looper-dude has noticed too and he's using original aaps version.

In 2.8.0 history was working

![Screenshot_20210112-204325_AndroidAPS.png](https://user-images.githubusercontent.com/45721291/104365249-0e27d680-5518-11eb-8969-f809dde47611.png)

**Comment by osodebailar** [comment] 2021-01-12 19:55
Yes , same here with 2.8.1.1

**Comment by rICTx-T1D** [comment] 2021-01-12 20:42
Maybe the l8cal database is empty after update from previous version... Give some hours or days and check it again.

**Comment by guydavies** [comment] 2021-01-12 20:44
It's been like that for over 24 hours but with 2.8.0.1 Dev then with 2.8.1.1

**Comment by guydavies** [comment] 2021-01-12 20:47
Sorry. Wrong issue.

**Comment by robertrub** [comment] 2021-01-13 09:18
I'm still in 2.7.0 and my history _opens_ empty too. But, if I hit the time button upper right, the data fils in. Give it a try.
I'll see how 2.8.1.1 works this afternoon.
![Screenshot_20210113-101439_AndroidAPS](https://user-images.githubusercontent.com/76626474/104431808-9fcf2c80-5588-11eb-890c-7f7af549310c.jpg)

**Comment by Alamo04** [comment] 2021-01-17 12:32
Confirmed in Master 2.8.1.1 and also in Dev. 2.8.1.2

**Comment by radu-neacsu** [comment] 2021-01-24 00:01
I think I found another related issue. If you add the carbs from nightscout they are not downloaded into the AAPS treatments. 
 Seems related. AAPS 2.8.0 working but 2.8.2 and 2.81.1 stopped importing/downloading information from nightscout

**Comment by robertrub** [comment] 2021-01-24 06:30
@radu-neacsu No, what you describe is not a bug but a feature :)
There is an bug in NS that caused errors in AAPS (too much insulin delivery) when data was D/Led from NS to AAPS. For security reasons, until the NS bug is resolved, AAPS will only UPLOAD to NS , D/L is turned off.

**Comment by radu-neacsu** [comment] 2021-01-24 08:33
@robertrub I wasn't aware of that. I will have some issues with this "feature". My system was dependent on the download feature. 
I am using Diabetes-m to calculate my meals, then a [python script](https://github.com/radu-neacsu/dm2nsc/blob/master/sync.py) that syncs the diabetes-m cloud with nightscout, and the AAPS is aware of what I eat.
Thanks for your response.

**Comment by robertrub** [comment] 2021-01-24 08:53
@radu-neacsu You can turn D/L from NS _ON_ if you put engineering mode but you should be well aware of the risks and the way they may or may not affect you.

**Comment by markvader** [comment] 2021-01-24 08:57
using engineering mode is the only way currently to switch NS_UPLOAD_ONLY to false.

**Comment by FreDiabetics** [comment] 2021-01-24 11:25
PLEASE OPEN A NEW ISSUE THID HAD NOTHING TO DO WITH THE MENTIONED PROBLEMS! THANK YOU

**Comment by szantos** [comment] 2021-01-26 14:32
Same history issues here, even with the NSClient app on another phone. Also present on 2.8.2

**Comment by AdrianLxM** [comment] 2021-02-09 11:47
Duplicate of https://github.com/nightscout/AndroidAPS/issues/217
Please follow updates there.

**Closed by AdrianLxM** 2021-02-09 11:47 UTC
