### ISSUE TITLE
[3.0-Beta5] Screen freezes when initializing Omnipod Eros

### ISSUE THREAD

**Issue by regiorunner** [nightscout/AndroidAPS#901] opened 2021-11-10 20:23 UTC
Phone: Moto 5 G5 Plus 6GB / 128GB
Android 11
3.0-Beta5

After succesful trial with Omnipod Dash switched back to Omnipod Eros.
After making the necessary changes and coupling the Rileylink prepared the Eros pod.
Entering "Activate Pod" and pressing in the bottom on "next" nothing seemed to happen.
After some time Android showed a message "APS does not seem to react. Close or wait?" I pressed "wait".
At that moment the Eros started clicking, indicating the initialization procedure was started.
When the clicking stopped (indicating initialization is finished) the correct screen appeared.
Pressing next to insert the canula the pop-up screen appears. Pressing "OK" freezes again the screen and again Android
showed the message  "APS does not seem to react. Close or wait?" Again pressed "wait".
After a few seconds the Pod starts clicking and the canula was inserted. The command was send correct to the Eros pod. After completion the correct screen appeared.
In the Pod tab pressing "updating status" works immediately, indicating connection to Eros pod is ok. Also injecting insuline and automatic basal aaptation works ok.
Did not encounter these problems initializing the Omnipod Dash, which uses simular screens.

If more info is needed please let me know. I do have the logfiles of course.

**Comment by betees82** [comment] 2021-11-10 21:43
Same Issue with Eros. There's now turning blue wheel during steps. 
![Uploading IMG_20211103_192404.jpg…]()

**Comment by StephenBrown2** [comment] 2021-11-10 21:46
Duplicate of https://github.com/nightscout/AndroidAPS/issues/782?

**Comment by betees82** [comment] 2021-11-10 21:48
> Duplicate of #782?

Looks like dublicate

**Closed** 2021-11-11 09:36 UTC

**Comment by regiorunner** [comment] 2021-11-11 15:31
It indeed looks like a duplicate of #782. Thanks for your comments.
