### ISSUE TITLE
DynamicISF safety limiter bug

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1349] opened 2022-02-20 09:42 UTC
@MilosKozak If I select the DynamicISF option, I have a safety limiter at 1.5 (mine is 10U) which may (or may not) come from my basal rate (0.5) x max multiplier (3).

![Screenshot_20220220-100849_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/154836862-3db20f8e-1651-4171-bb06-57bccb451132.jpg)

This is a game stopper of course ;) No more SMBs, no more high basals etc.

If I select OpenSMB, the same limiter goes to 22.

![Screenshot_20220220-102857_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/154836921-c6e01ea1-6bb9-41a1-97e2-fe80f516b774.jpg)

**Comment by philipgo** [comment] 2022-02-20 10:03
Same problem with latest dev and AutoISF here.

**Comment by bchris21** [comment] 2022-02-20 10:25
Same here (3.0.0.1-dev-a) but with different value, maybe because it refers to "child" profile.

Screenshot with SMB last run on 10:56 is with Dynamic ISF

![Screenshot_20220220_112134.jpg](https://user-images.githubusercontent.com/4725280/154838234-b350529c-a3da-42b3-a090-8a869dd74b1a.jpg)

Screenshot with SMB last run on 11:00 is with OpenAPS SMB plugin.

![Screenshot_20220220_112154.jpg](https://user-images.githubusercontent.com/4725280/154838254-bff588ff-63df-4a44-aa04-3bd6af3b3e2c.jpg)

**Comment by Alamo04** [comment] 2022-02-20 11:11
Confirm, same here.

**Comment by elgrupo123** [comment] 2022-02-20 12:44
unfortunately also here.  IOB max 4IU

**Comment by vanelsberg** [comment] 2022-02-20 13:39
Confirming,
Duplicate of https://github.com/nightscout/AndroidAPS/issues/1346

**Comment by swissalpine** [comment] 2022-02-20 16:34
Please note: The first commit (https://github.com/swissalpine/AndroidAPS-1/commit/a0c3fad06ea3dad73e3819794e7889e427ccb664) is wrong, the second works for me:
https://github.com/swissalpine/AndroidAPS-1/commit/6a961eb4d8b949ff8564bcd17f0f3b2469e0beda

**Closed** 2022-02-20 17:26 UTC

**Comment by Alamo04** [comment] 2022-02-20 17:56
@MilosKozak @swissalpine 
There are 2 DynamicISF errors in building the App, looks like kotlin errors.
Think they are not importand and self fixed in this version.
![Unbenannt](https://user-images.githubusercontent.com/36486505/154856684-aeb75d67-a6c3-4c80-b4aa-2d959cab56a8.PNG)
