### ISSUE TITLE
Last Dev-C : lost connection to watch face

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2172] opened 2022-11-07 17:04 UTC
![Screenshot_20221107_172151.jpg](https://user-images.githubusercontent.com/76626474/200370437-cb4bb13b-cd9c-4256-952e-3f3d50f07870.jpg)

@MilosKozak I lost connection to watch face after updating the phone apk and watch apk to the last dev-c.

New apk on phone and 3 days  "old" apk on watch did not communicate either.

**Comment by overfrenk** [comment] 2022-11-07 20:53
Same for me! Samsung watch4

**Comment by robertrub** [comment] 2022-11-08 00:35
To be more precise, AAPS Wear menu has the correct watch name (thus is connected) but BGs COB and IOB ate stale, not updated (even when I hit send resend dll data to watch.

**Comment by robertrub** [comment] 2022-11-08 17:26
![Screenshot_20221108_182459.jpg](https://user-images.githubusercontent.com/76626474/200633659-48c0ecb9-1253-46bd-96c0-b68a94e31a10.jpg)

This version does not solve the connection problem to the watch.

**Comment by Andries-Smit** [comment] 2022-11-11 15:13
Duplicate of #2168

**Comment by Andries-Smit** [comment] 2022-11-12 19:07
Issue is caused be depended libraries that are old, to make them work on modern Android, jettifier could be used. However this was disabled in commit https://github.com/nightscout/AndroidAPS/commit/e7c41beab74306ee3b5c68c41aac9bf05da36034

(Also the preference menu is impacted)

Probable reason, it slows the build. I could recommend "pre-jetifier" the decencies as described here.
https://adambennett.dev/2020/08/disabling-jetifier/

For all inpatient, that do not want to way on a fix, just enable jetifier again, and rebuild

**Closed** 2022-11-13 16:18 UTC

**Comment by robertrub** [comment] 2022-11-13 16:59
Hi @Andries-Smit 

You last modifications did the job. The watchface is working again. Tnx a lot. 

Robby
