### ISSUE TITLE
Minor esthetic bug : Black on gray text

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1425] opened 2022-03-09 08:53 UTC
This "bug" was solved for carb entries #1376  but is still in preferences.

There are black "buttons" on gray background in the preference settings. It is very classy and chic but not the most visible combination.

![Screenshot_20220309-094910_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/157406584-2298b1bf-aa30-44e8-ba9a-1672a5c88ce4.jpg)

**Comment by mick711** [comment] 2022-03-09 20:34
![Screenshot_20220309-213316041](https://user-images.githubusercontent.com/441734/157531072-ce58d39f-28a6-44d6-98b8-dbccef1bd18e.jpg)

Same with Filtre on the top

**Comment by Andries-Smit** [comment] 2022-03-10 11:27
The text color on buttons are based on `colorPrimary`. The night theming, is not using the default style correctly. This requires a bit of rework. There are some plans the cleanup and consolidate styling.

**Comment by osodebailar** [comment] 2022-03-10 11:30
Its solved in the Themeswitcher branch for the light and dark mode. 
There must be planned to merge it in the future and apps has a real material theme and so we can change and adapt Color's as we want

**Comment by Philoul** [comment] 2022-03-11 12:01
Hi Andreas,

Are number picker fixed in your light/dark mode PRs (#1430 and/or #436) ?
(Horizontal is a bit better than vertical number, but none of bath are "perfect" currently)
![image](https://user-images.githubusercontent.com/52934600/157862911-b731863f-f795-4360-8643-8e45a0a72685.png)

**Comment by osodebailar** [comment] 2022-03-11 12:23
In my https://github.com/nightscout/AndroidAPS/pull/326 they look 
![Uploading pcicker_hor.PNG…]()
![picker_ver](https://user-images.githubusercontent.com/25795894/157866140-c2346bc0-be9d-4631-9b5a-17627d979629.PNG)

**Comment by Philoul** [comment] 2022-03-19 11:59
It's better on latest version but can be improved for numberpicker I think:
"-" is too small in horizontal number picker
"+" is not vertical centered (vertical and horizontal numberpickers), the bottom is troncated (vertical numberpicker) and has not same size (horizontal + bigger than vertical +) ...

![image](https://user-images.githubusercontent.com/52934600/159120045-139b5e5c-06cf-417a-a66b-5d5d4dccbe34.png)

**Comment by osodebailar** [comment] 2022-03-19 12:24
> It's better on latest version but can be improved for numberpicker I think: "-" is too small in horizontal number picker "+" is not vertical centered (vertical and horizontal numberpickers), the bottom is troncated (vertical numberpicker) and has not same size (horizontal + bigger than vertical +) ...
> 
> ![image](https://user-images.githubusercontent.com/52934600/159120045-139b5e5c-06cf-417a-a66b-5d5d4dccbe34.png)

The only way i see is that we try to replace + and - with svg graphics. maybe we have the right ones in fontawsome ?

**Comment by Philoul** [comment] 2022-03-19 14:10
On latest dev-g, the header of pugin in hamburger menu is no more visible (#1460), could it be a regression due to #1458?

**Comment by osodebailar** [comment] 2022-03-19 14:50
> On latest dev-g, the header of plugin in hamburger menu is no more visible (#1460), could it be a regression due to #1458?

solved in https://github.com/nightscout/AndroidAPS/pull/1463

**Comment by MilosKozak** [comment] 2022-03-19 16:39
@osodebailar ProfileHelper should be `AppTheme_NoActionBar` but this still has wrong colors

**Comment by osodebailar** [comment] 2022-03-19 16:46
> 

i will have a look

**Comment by robertrub** [comment] 2022-03-19 19:34
On the latest build tonight, the minus seems tiny and the plus is too low on my phone (S9 Android 10)

![Screenshot_20220319-200706_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/159135780-be5d8d65-f8b8-4ea9-8068-1e1f5b62c83b.jpg)

![Screenshot_20220319-203251_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/159135786-a0dcef40-4aad-4f0e-b427-0955db65dcc2.jpg)

**Comment by kristinsmotz** [comment] 2022-03-19 23:59
> 

Same here on Huawei P30 Pro (And in NSClient on Samsung Galaxy ZFlip3). Built just now 30 minutes ago. 
![275993099_411134350820171_2798658707185498463_n](https://user-images.githubusercontent.com/71758682/159142408-e9bf8687-6e73-421e-ae75-f1923dbb9b0f.jpg)
![275897705_1096541204525636_5318776353662827006_n](https://user-images.githubusercontent.com/71758682/159142409-0689cbda-ed7d-4a68-8968-184935dbc7fe.jpg)

**Comment by Philoul** [comment] 2022-03-20 08:45
And some regression on other ok/cancel popup:
![Screenshot_20220320-094116_AndroidAPS.jpg](https://user-images.githubusercontent.com/52934600/159154834-70de8f0a-8ccc-45f9-ada6-3c0829988750.jpg)
![Screenshot_20220320-094202_AndroidAPS.jpg](https://user-images.githubusercontent.com/52934600/159154849-67e11abf-c367-4734-9664-4c41c92572af.jpg)

**Comment by parapenT1sta** [comment] 2022-03-20 11:59
Black text is also present in Treatments option after introducing the value for insulin or carbs.

**Comment by parapenT1sta** [comment] 2022-03-20 11:59
![Uploading Screenshot_20220320-115556.png…]()

**Comment by parapenT1sta** [comment] 2022-03-20 12:00
![Screenshot_20220320-115556](https://user-images.githubusercontent.com/608650/159161189-af23785c-2daa-44d7-890f-080ec285ddee.png)

**Comment by osodebailar** [comment] 2022-03-20 12:11
No other screenshots needed .
The reason is in all situation the same .
( Mainactivity is not in the „real dark Mode „ )
Solve ist when I am back at home today evening or tomorrow morning.

**Closed** 2022-04-07 11:54 UTC
