### ISSUE TITLE
Overlapping Times in basal Tab leading to wrong iob? Dev-i

### ISSUE THREAD

**Issue by Ede1975** [nightscout/AndroidAPS#1597] opened 2022-04-10 15:47 UTC
It seems tbrs have not been cancelled, Times are overlapping in basal tab
Possibly aaps was out of reach of dash a couple of Times during the period from 14:53 to 16:53

![IMG-20220410-WA0000.jpg](https://user-images.githubusercontent.com/88888180/162627614-4d46bc2e-aa0b-454b-a5bb-f0dc0b09acf4.jpg)

![AndroidAPS_LOG_1649605049645.log.zip](https://github.com/nightscout/AndroidAPS/files/8459360/AndroidAPS_LOG_1649605049645.log.zip)

**Comment by MilosKozak** [comment] 2022-04-13 11:42
is it possible you changed pump meanwhile?

**Comment by Ede1975** [comment] 2022-04-13 12:01
You mean from dash to some other pump or virtual pump? No, definately not.

**Comment by MilosKozak** [comment] 2022-04-14 07:41
do you have logs prior this one?

**Comment by MilosKozak** [comment] 2022-04-14 07:42
note: where is this from
`17:02:30.229 [RxCachedThreadScheduler-53] D/DATABASE: [PumpSyncImplementation.syncTemporaryBasalWithPumpId():274]: Updated TemporaryBasal TemporaryBasal(id=28452, version=3, dateCreated=1649602950162, isValid=true, referenceId=null, interfaceIDs_backing=InterfaceIDs(nightscoutSystemId=null, nightscoutId=6251f4b9215b0200041e4d4c, pumpType=OMNIPOD_DASH, pumpSerial=4241, temporaryId=null, pumpId=-8976659072097442112, startId=null, endId=-7142919318749436032), timestamp=1649602949159, utcOffset=7200000, type=NORMAL, isAbsolute=true, rate=1.5, duration=1800000)
`

**Comment by Ede1975** [comment] 2022-04-14 08:27
> do you have logs prior this one?

No, unfortunately not. I am still on the same Version, did not happen again. In case it occurs again i will add new logs.

**Comment by emmatovar27** [comment] 2022-04-20 01:06
Hi There! I have the same issue. This happens every time the TBR is set for 30 min. The rest of TBR looks to work fine.
![Screenshot_20220419-175209](https://user-images.githubusercontent.com/39507448/164126009-186010bd-c76c-4cb3-a94e-5c3c46640a10.png)
[AndroidAPS_LOG_1650416536289log.zip](https://github.com/nightscout/AndroidAPS/files/8517378/AndroidAPS_LOG_1650416536289.log.zip)

 Let me know if there is anything additional information is need. 

I'm using the dev branch from Philoul to test Autotune.

**Comment by vanelsberg** [comment] 2022-04-25 18:50
Could not confirm but now seeing similar, quite a lot of this overlapping TBR's at certain times.
Am running DASH while building from Philoul's Autotune PR (merged with latest dev).

Will switch back building form current dev to see if it reproduces with some helpfull logging
@MilosKozak Any suggestions on how to "debug" this. Assuming at least logfiles - anything else to watch for?

![xxScreenshot_20220425-203657_AndroidAPS](https://user-images.githubusercontent.com/45144129/165153471-25fade52-d314-419b-bf44-a47b36cb20a8.jpg)

**Comment by nicoleloop** [comment] 2022-04-25 21:56
I am experiencing the same issues with my Dash Pods, as well as terrible bluetooth connections with the last 4 pods. In the range of the lowest, 51% to the highest being 63% connection quality.

**Comment by MilosKozak** [comment] 2022-04-26 08:43
@vanelsberg do you have logs from this time?

**Comment by robertrub** [comment] 2022-04-26 11:00
I started looking and found that I have the same bug

![Screenshot_20220426-125720_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/165285949-6ec7f899-ccee-4af7-aa5b-7d99f0d81b99.jpg)

**Comment by vanelsberg** [comment] 2022-04-26 13:11
> ... try dev and provide logs
Busy trying to repro and have logging/screenprints. Expect real soon now...

**Comment by vanelsberg** [comment] 2022-04-26 19:52
@MilosKozak Omipod DASH, now running latest dev builds from yesterday/today. Also seeing overlapping TBR.
(Note that I am running an outdated version of NS - do not think this is relevant?)

Have 2 sets of logging with additional screenshots
Also adding .zip if the complete AAPS logging for today:

[1.zip](https://github.com/nightscout/AndroidAPS/files/8566414/1.zip)
[2.zip](https://github.com/nightscout/AndroidAPS/files/8566415/2.zip)
[morelog.zip](https://github.com/nightscout/AndroidAPS/files/8566416/morelog.zip)

--------------------------------------------------
![about](https://user-images.githubusercontent.com/45144129/165380685-8835c519-d5ed-402a-a264-6c1504d424f3.jpg)
![Screenshot_20220426-150441_AndroidAPS](https://user-images.githubusercontent.com/45144129/165380700-90dda422-33b9-45a7-985a-65ac73ef1b95.jpg)

**Comment by vanelsberg** [comment] 2022-04-26 19:54
Did not come to checking logs myself, maybe tomorrow...
If you need additional info of specific testing, no problem, let me know...

**Comment by robertrub** [comment] 2022-04-26 23:26
It is a killer... I'm not sure going on using _dev_

![Screenshot_20220427-012100_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/165408535-3662ef2c-1b45-4085-98ff-3adfb0957d52.jpg)

![AndroidAPS._2022-04-26_17-36-40_.11.zip](https://github.com/nightscout/AndroidAPS/files/8567468/AndroidAPS._2022-04-26_17-36-40_.11.zip)

![AndroidAPS._2022-04-27_00-00-07_.0.zip](https://github.com/nightscout/AndroidAPS/files/8567476/AndroidAPS._2022-04-27_00-00-07_.0.zip)

![AndroidAPS._2022-04-27_00-00-07_.1.zip](https://github.com/nightscout/AndroidAPS/files/8567478/AndroidAPS._2022-04-27_00-00-07_.1.zip)

**Comment by robertrub** [comment] 2022-04-27 04:05
I went back to _Master_ 3.0.0.1 and overlapping TBRs stopped.

**Comment by vanelsberg** [comment] 2022-04-27 08:00
Screenprint showing overlap + logging (lots - had logging of events enabled - switched this off now)
[20220427.zip](https://github.com/nightscout/AndroidAPS/files/8570101/20220427.zip)

**Comment by robertrub** [comment] 2022-04-27 13:11
After 12h of use, I confirm that the TBR overlapping issue does not exist in _master v3.0.0.1_.

**Comment by mick711** [comment] 2022-04-27 18:12
![Screenshot_20220427-200812044](https://user-images.githubusercontent.com/441734/165591901-2e3f638e-c5e5-4dfd-b8b0-5fb0d90467c2.jpg)
![Screenshot_20220427-200823761](https://user-images.githubusercontent.com/441734/165591913-1e9528f2-e7a2-4e71-b9be-9ac884803096.jpg)
Last dev i 
[Uploading AndroidAPS.log…]()

**Comment by nicoleloop** [comment] 2022-04-27 22:38
I was woken up 3 times last night by low bg events alarms. Does anyone have any idea what's happening? Can't we just revert the last month of dev updates and start over? I am worried that this is going to cause something worse than just having alarms go off, like not being any to wake up because AAPS hadn't recognized or recorded 118 +111 minutes of basal! My low event last night was so pronounced that I walked into the wall of my own bedroom and then crumpled on the floor. My bg registered 26mg/dL when I checked it with my meter. At this point I would support reverting all of the last month's worth of commits on the Dev branch, as this is a very dangerous bug!



Sent from my T-Mobile 5G Device



-------- Original message --------
From: mick711 ***@***.***>
Date: 4/27/22 11:12 AM (GMT-08:00)
To: nightscout/AndroidAPS ***@***.***>
Cc: nicoleloop ***@***.***>, Comment ***@***.***>
Subject: Re: [nightscout/AndroidAPS] Overlapping Times in basal Tab leading to wrong iob? Dev-i (Issue #1597)


[Screenshot_20220427-200812044]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F441734%2F165591901-2e3f638e-c5e5-4dfd-b8b0-5fb0d90467c2.jpg&data=05%7C01%7C%7C5024ee6af1194ee636a308da2879867b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637866799664227550%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RhK6M4cbf94%2BAg6vDRRDv1u%2BLvGmvHI9r1%2FXnv4QbsI%3D&reserved=0>
[Screenshot_20220427-200823761]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F441734%2F165591913-1e9528f2-e7a2-4e71-b9be-9ac884803096.jpg&data=05%7C01%7C%7C5024ee6af1194ee636a308da2879867b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637866799664227550%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=W65pNoxF%2F1b1w2hOgZR3elvP4uXFzwyLFBgsjHkZ4vk%3D&reserved=0>
Last dev i
Uploading AndroidAPS.log…

**Comment by nicoleloop** [comment] 2022-04-27 22:43
Sent from my T-Mobile 5G Device



-------- Original message --------
From: nicoleloop ***@***.***>
Date: 4/27/22 3:38 PM (GMT-08:00)
To: nightscout/AndroidAPS ***@***.***>
Cc: nicoleloop ***@***.***>, Your activity ***@***.***>
Subject: Re: [nightscout/AndroidAPS] Overlapping Times in basal Tab leading to wrong iob? Dev-i (Issue #1597)


I was woken up 3 times last night by low bg events alarms. Does anyone have any idea what's happening? Can't we just revert the last month of dev updates and start over? I am worried that this is going to cause something worse than just having alarms go off, like not being any to wake up because AAPS hadn't recognized or recorded 118 +111 minutes of basal! My low event last night was so pronounced that I walked into the wall of my own bedroom and then crumpled on the floor. My bg registered 26mg/dL when I checked it with my meter. At this point I would support reverting all of the last month's worth of commits on the Dev branch, as this is a very dangerous bug!



Sent from my T-Mobile 5G Device



-------- Original message --------
From: mick711 ***@***.***>
Date: 4/27/22 11:12 AM (GMT-08:00)
To: nightscout/AndroidAPS ***@***.***>
Cc: nicoleloop ***@***.***>, Comment ***@***.***>
Subject: Re: [nightscout/AndroidAPS] Overlapping Times in basal Tab leading to wrong iob? Dev-i (Issue #1597)


[Screenshot_20220427-200812044]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F441734%2F165591901-2e3f638e-c5e5-4dfd-b8b0-5fb0d90467c2.jpg&data=05%7C01%7C%7C5024ee6af1194ee636a308da2879867b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637866799664227550%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RhK6M4cbf94%2BAg6vDRRDv1u%2BLvGmvHI9r1%2FXnv4QbsI%3D&reserved=0>
[Screenshot_20220427-200823761]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F441734%2F165591913-1e9528f2-e7a2-4e71-b9be-9ac884803096.jpg&data=05%7C01%7C%7C5024ee6af1194ee636a308da2879867b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637866799664227550%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=W65pNoxF%2F1b1w2hOgZR3elvP4uXFzwyLFBgsjHkZ4vk%3D&reserved=0>
Last dev i
Uploading AndroidAPS.log…

**Comment by jgslade** [comment] 2022-04-28 04:33
I got an overlapping basal today. Looking into what was going on at the time,  it looks like a tbr was set,  an smb was delivered,  an automation was triggered setting a temp target, then another tbr was set. 

![Screenshot_20220427-215332_AndroidAPS](https://user-images.githubusercontent.com/29897815/165676730-be897c6f-7096-4623-b494-c727b1ff8a93.jpg)

[AndroidAPS._2022-04-27_00-00-09_.4.zip](https://github.com/nightscout/AndroidAPS/files/8579512/AndroidAPS._2022-04-27_00-00-09_.4.zip)

**Comment by nicoleloop** [comment] 2022-04-28 06:19
I have yet to look in the log files to verify this info, but right off the top of my head- temp basals are affected in this way, but not SMBs.



Sent from my T-Mobile 5G Device



-------- Original message --------
From: jgslade ***@***.***>
Date: 4/27/22 9:33 PM (GMT-08:00)
To: nightscout/AndroidAPS ***@***.***>
Cc: nicoleloop ***@***.***>, Comment ***@***.***>
Subject: Re: [nightscout/AndroidAPS] Overlapping Times in basal Tab leading to wrong iob? Dev-i (Issue #1597)


I got an overlapping basal today. Looking into what was going on at the time, it looks like a tbr was set, an smb was delivered, an automation was triggered setting a temp target, then another tbr was set.

[Screenshot_20220427-215332_AndroidAPS]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F29897815%2F165676730-be897c6f-7096-4623-b494-c727b1ff8a93.jpg&data=05%7C01%7C%7Ccb0a6113f4fd4702c49a08da28d03de8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637867172105993931%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QS4fY%2BOufpBCTIIuba1Y9cKJ21Cmbm2Ya7sTwYUNEmQ%3D&reserved=0>

AndroidAPS.2022-04-27_00-00-09.4.zip<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnightscout%2FAndroidAPS%2Ffiles%2F8579512%2FAndroidAPS._2022-04-27_00-00-09_.4.zip&data=05%7C01%7C%7Ccb0a6113f4fd4702c49a08da28d03de8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637867172105993931%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Sme4FGHOhOWUJmoUZFOLA9u%2FOl%2B41S963UlEcuG1PnA%3D&reserved=0>

**Comment by tswire** [comment] 2022-04-28 19:26
Has anyone confirmed if this truly results in incorrect IOB?  More importantly, if that IOB is used in the predictions and AAPS dosing decisions?  I think it's very obvious that something is "wrong" based on the treatments tab for TB.  However, I think we need to know immediately and urgently if this could be dangerous, as seen by a few examples of people going low.

**Comment by vanelsberg** [comment] 2022-04-28 21:34
> I was woken up 3 times last night by low bg events alarms.
Same here a number of times.
As far as I could tell the much-argued negative IOB problem: too much insulin causing high negative insulin buildup that AAPS will try to fill in as soon as BGs are rising - followed by another low as logic dictates. This could be a side-effect?

Not sure, but I do think we need confirmation that the TBR problems we see are not affecting IOB calculations. I could switch back to release version, but then I would not be able to help document/analyse/solve this problem. So will stay on dev as long as I think is safe enough.

**Comment by Ede1975** [comment] 2022-04-29 04:41
> Has anyone confirmed if this truly results in incorrect IOB?  More importantly, if that IOB is used in the predictions and AAPS dosing decisions?  I think it's very obvious that something is "wrong" based on the treatments tab for TB.  However, I think we need to know immediately and urgently if this could be dangerous, as seen by a few examples of people going low.   

From my point of view its obvious that it affects iob calculations. It counts (negative) insulin twice when Times overlap. If you remove an overlapping treatment (which is Not 0 yet) , the calculated iob changes instantly. Same for positive overlaps of course.

**Comment by vanelsberg** [comment] 2022-04-29 14:58
This issue is labeled "DASH".
Is it only for Omnipod DASH pump the overlapping TBR is occurring?

**Comment by MilosKozak** [comment] 2022-04-29 17:13
i improved logging https://github.com/nightscout/AndroidAPS/commit/2d653c67ef9c32201fe0e28897af4904f9c423cb
i'd need someone to reset AAPS DB (with zero IOB COB to be safe) and try latest dev
Provide logs if you see this again

**Comment by vanelsberg** [comment] 2022-04-29 18:32
> i improved logging [2d653c6](https://github.com/nightscout/AndroidAPS/commit/2d653c67ef9c32201fe0e28897af4904f9c423cb) i'd need someone to reset AAPS DB (with zero IOB COB to be safe) and try latest dev Provide logs if you see this again

@MilosKozak About to build, reset database and then watch for repro.
Expect logging as soon as I have some.

**Comment by vanelsberg** [comment] 2022-04-29 18:42
> i improved logging [2d653c6]...

Provide logs if you see this again
Any special log settings to eneable?

**Comment by MilosKozak** [comment] 2022-04-29 21:11
PUMP*

**Comment by mick711** [comment] 2022-04-30 16:30
![Screenshot_20220430-182631682](https://user-images.githubusercontent.com/441734/166114055-14232ffe-cd0d-402e-9f18-c1ad910eeb78.jpg)
![Screenshot_20220430-182616600](https://user-images.githubusercontent.com/441734/166114057-3f81f2f5-b5da-489c-8ac0-8f1855c8068f.jpg)
I try to find différence Master and Dev

**Comment by vanelsberg** [comment] 2022-04-30 19:38
> PUMP*
@MilosKozak 
Yesterday evening install latest dev, did database reset: until now (24hrs) no overlap.
(detail: pump connection is 100%, so no fail/retries on commands - will test later if any relation with failures?)

(Expect logging as soon as I see overlapping occur)

**Comment by emmatovar27** [comment] 2022-04-30 20:56
> 

Same Here! :)

TBR is not overlapping anymore! 

Thanks @MilosKozak 

![TempBasalRates](https://user-images.githubusercontent.com/39507448/166122364-6af6dc19-b192-437b-a854-db1e265a085e.png)

**Comment by nicoleloop** [comment] 2022-04-30 22:34
Wonderful! Thanks Milos! 😁



Sent from my T-Mobile 5G Device



-------- Original message --------
From: emmatovar27 ***@***.***>
Date: 4/30/22 1:56 PM (GMT-08:00)
To: nightscout/AndroidAPS ***@***.***>
Cc: nicoleloop ***@***.***>, Comment ***@***.***>
Subject: Re: [nightscout/AndroidAPS] Overlapping Times in basal Tab leading to wrong iob? Dev-i (Issue #1597)


Same Here! :)

TBR is not overlapping anymore!

Thanks @MilosKozak<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMilosKozak&data=05%7C01%7C%7Cc0ccc8eeb36340b31c7108da2aebdbf3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637869489736324622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LlkDL4ewME1wLOqNA2eXlT1x49GyJxP91xu%2Fmjvq%2B8o%3D&reserved=0>

[TempBasalRates]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F39507448%2F166122364-6af6dc19-b192-437b-a854-db1e265a085e.png&data=05%7C01%7C%7Cc0ccc8eeb36340b31c7108da2aebdbf3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637869489736324622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CQ%2F0wvcI6JSLnEp2WWSN17rr6Wk2YthdmmIs40a3YVI%3D&reserved=0>

**Comment by vanelsberg** [comment] 2022-05-01 12:36
After 2 days, with new build and database reset, still not seeing anything on TBR overlapping.
Wondering if database could be a factor in causing this?

**Comment by ArthurusDent** [comment] 2022-05-01 14:31
@vanelsberg If this is the same bug I saw, it might only happen when disabling the pump für 2 h. Didn't notice it with shorter periods but I might just not have noticed. Could you maybe test 2 h, too?: Disabling the pump for 2 h, waiting for the algorithm to run once and then re-enabling the pump again?

**Comment by MilosKozak** [comment] 2022-05-02 21:46
i believe it was corrupted data

**Comment by vanelsberg** [comment] 2022-05-03 06:01
> .. i believe it was corrupted data

@MilosKozak Was thinking the same. Had been testing autotune on separate branch. Now on dev latest dev branch with databases reset, but still:
Overlap again past night (see 20220503, 02:59h, 04:59h,)

Coincided with two G6 abnormalities where it started alerting low (while initially on target) needing carbs (partly unregistered). 
Not sure if this could be related. See screenprints G6 and FSL I have additionally active for testing/comparance.

**All logging/info:**
[20220503.zip](https://github.com/nightscout/AndroidAPS/files/8608440/20220503.zip)

**Screenshots;**
![Screenshot_20220503-062541_AndroidAPS](https://user-images.githubusercontent.com/45144129/166409870-e9fd7b3f-2d59-4f62-94ce-2c20e127da1f.jpg)
![Screenshot_20220503-062448_AndroidAPS](https://user-images.githubusercontent.com/45144129/166409876-84ec58cb-3cd7-4a15-a36e-823e3117318e.jpg)

**Comment by MilosKozak** [comment] 2022-05-03 08:21
if I see correctly the fixing commit is not included in autotune branch
https://github.com/nightscout/AndroidAPS/commit/1684b88270b34d0205f3e10ad3109e2319802532

**Comment by tswire** [comment] 2022-05-03 12:36
> if I see correctly the fixing commit is not included in autotune branch [1684b88](https://github.com/nightscout/AndroidAPS/commit/1684b88270b34d0205f3e10ad3109e2319802532)

But he said this overrlapping was from updated Dev (as of yesterday) and after resetting DB?  So that commit was 20 days ago and not sure how that fits in to this?

**Comment by jgslade** [comment] 2022-05-03 13:15
I got some overlapping tbrs last night.  Using the issue with improved logging and reset the db after updating.

The 10:34-11:04 and 10:59-11:09 one is interesting because it's the same tbr value.  

![Screenshot_20220503-070437_AndroidAPS](https://user-images.githubusercontent.com/29897815/166459114-ee179059-4679-49ca-b324-4b8a176f5b97.jpg)

[AndroidAPS._2022-05-02_21-47-20_.1.zip](https://github.com/nightscout/AndroidAPS/files/8610629/AndroidAPS._2022-05-02_21-47-20_.1.zip)

**Comment by vanelsberg** [comment] 2022-05-03 14:46
> if I see correctly the fixing commit is not included in autotune branch

FYI: Not using autotune branch but latest "dev" #7d93a2ceef

**Comment by kristinsmotz** [comment] 2022-05-03 20:46
yesterday found the first overlapping TBR's I have noticed. We're on Dash, and testing Dynamic ISF on the second latest version (Dynamic ISF beta 1.6.1). What was interesting to me was that it occurred in the same timeframe where I encountered the first re-occurance of my other issue (https://github.com/nightscout/AndroidAPS/issues/1667 where bolus doses (and SMB's) occasionally don't show up in the NSClient phone, only in AAPS phone and on our nightscout site), since I cleared out memory and cache related to NSClient on my phone a few days ago. Could these issues be related in any way? Since clearing database (or in my case clearing phone memory) appears to help for a period of time, could it have anything to database structure/save data file size?

**Comment by avereha** [comment] 2022-05-04 07:15
Can you please to disable Nightscout sync and check if the issue is still there?

**Comment by vanelsberg** [comment] 2022-05-04 19:17
> Can you please to disable Nightscout sync and check if the issue is still there?

Would setting NSClient to "Paused" (checkbox) do?

**Comment by avereha** [comment] 2022-05-04 19:26
yes

**Comment by vanelsberg** [comment] 2022-05-04 22:00
First results. Will run this for some time trying to "leave it alone" and post new logs here once overlapping happens.

Did update to new build for #1691 around 21:45h (?).
Now seeing this. Not sure: why are these most recent TBRs suddenly with only a starting time?

See "22:11-22:41 1.75U/h 30 mins":
It was canceled (also on DASH history) but somehow this was not registered to AAPS?

![Screenshot_20220504-234400_AndroidAPS](https://user-images.githubusercontent.com/45144129/166831365-ff1f96e3-1a6d-4a0f-ac5d-ad7376690d3b.jpg)

** Log files + screenshot **
[20220504.zip](https://github.com/nightscout/AndroidAPS/files/8627412/20220504.zip)

**Comment by jgslade** [comment] 2022-05-04 22:39
I turned off nightscout syncing this morning,  checked this afternoon and I've still got overlapping basals.
![Screenshot_20220504-163236_AndroidAPS](https://user-images.githubusercontent.com/29897815/166836657-5079f90d-9e49-4909-a132-dd0295947b9e.jpg)
[AndroidAPS._2022-05-04_00-00-00_.2.zip](https://github.com/nightscout/AndroidAPS/files/8627781/AndroidAPS._2022-05-04_00-00-00_.2.zip)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/8627782/AndroidAPS.log)

**Comment by vanelsberg** [comment] 2022-05-05 06:46
Lots of TBR overlap (see 00:00 ... 03:00h)?

![Screenshot_20220505-083933_AndroidAPS](https://user-images.githubusercontent.com/45144129/166874267-22419778-c8db-4297-9062-3d9a1ffef231.jpg)

** Logfiles & screenprint **
[20220505-1.zip](https://github.com/nightscout/AndroidAPS/files/8629169/20220505-1.zip)

**Comment by MilosKozak** [comment] 2022-05-05 13:56
looks like AAPS is updating old records.
i added more logging to dev https://github.com/nightscout/AndroidAPS/commit/d131ceb4bd52e85d92650f6dff26692f73d822de
please again update and reset db + pause NSClient

**Comment by MilosKozak** [comment] 2022-05-05 13:57
maybe remove old logs too and once this happen upload all available logs (if there are not too many)

**Comment by vanelsberg** [comment] 2022-05-06 23:49
@MilosKozak @avereha 
Have been running commit #3d9b08e5c2 with NS paused for 24 hrs: no overlap.
With it, BG's are steady as rock again. Maybe to early to conclude NS is the problem. Wil wait for another 12 hrs. Then "unpause" NS to see what happens. Expect logging as soon as overlap happens again.

**Comment by vanelsberg** [comment] 2022-05-08 21:01
> Have been running commit #3d9b08e5c2 with NS paused for 24 hrs: no overlap.

Still not seeing any overlap happening. Tried syncing NS by temporarily unpausing NS until synced (then pause again):  no overlap.

Switched to new phone yesterday evening (read started with new database).
Now running for about 24 hours. Will enable NS syncing to see if this results in overlap occurring.

**Comment by vanelsberg** [comment] 2022-05-09 18:56
@avereha @MilosKozak More logs.

Was unable to reproduce TBR overlapping with NSClient paused. Temporary unpausing NSClient to catch up syncing (and then pausing again when don) did not give problems.

Switched to a new phone yesterday, so empty database, clean OS, clean install.
Today, unpaused NSClient and TBR overlapping started occurring again. Looks like NS syncing introduces/relates to this problem?

Screenshots and logging attached below. Please let me know when I can assist any further in finding the problem!

[20220509.zip](https://github.com/nightscout/AndroidAPS/files/8654463/20220509.zip)

**Comment by MilosKozak** [comment] 2022-05-10 18:40
hopefully fixed by #1715 
open new issue if the problem persists

**Closed by MilosKozak** 2022-05-10 18:40 UTC
Labels: omnipod dash

**Comment by ArthurusDent** [comment] 2022-05-10 18:52
It looks like #1715 only fixes Dash. I'm on regular 3.0.0.1 and Medtronic and I'm seeing this bug. Could somebody please check the Medtronic plugin? Thanks!

**Comment by MilosKozak** [comment] 2022-05-11 09:20
@ArthurusDent open new MDT specific issue with logs and info
