### ISSUE TITLE
APS 2.8.2.18 Sprit distance timestamp error in the timer

### ISSUE THREAD

**Issue by Thomas-Wolff** [nightscout/AndroidAPS#1116] opened 2022-01-01 18:20 UTC
There is a periodic error in the timer when bolusing meals via the bolus suggestion calculator with a syringe interval. Carbohydrates were triggered with an interval of 10 minutes, in the timer these 10 minutes were not set but only 1 minute. In the APS main screen and treatment tab everything was booked and set correctly. Only affects the timer for the carbohydrate intake.

If I can trace it correctly, this error occurred for the first time with the build: aee036e2 from 29.12.2021.

Enclosed are the corresponding screnshots and log file.

With the request to check, and best thanks Thomas

![Bild1](https://user-images.githubusercontent.com/59526802/147857440-01f9f307-6a0e-40da-9e57-cdd76a13bafe.jpg)

![Bild2](https://user-images.githubusercontent.com/59526802/147857450-df5359f3-7693-435b-af85-fe979a3029c5.jpg)

![Bild3](https://user-images.githubusercontent.com/59526802/147857457-9164f6cd-0b18-470c-b8f4-af8d5bb83ed5.jpg)

![Bild4](https://user-images.githubusercontent.com/59526802/147857460-8a7d9df0-1c1c-4902-8a6c-23ecfb58cfd6.jpg)

[AndroidAPS._2022-01-01_12-29-10_.10.zip](https://github.com/nightscout/AndroidAPS/files/7798058/AndroidAPS._2022-01-01_12-29-10_.10.zip)

**Comment by AdrianLxM** [comment] 2022-01-02 13:09
Thanks for reporting.
I guess the issue is with having a`Long` passed as time instead of an `Int`.
I'll PR a possible fix in the course of the day.

**Comment by Thomas-Wolff** [comment] 2022-01-02 13:19
Thanks for the information, I had already suspected something like that.

**Comment by AdrianLxM** [comment] 2022-01-02 13:32
To be fair, I didn't even get the timer to start on my phone with `Long` as datatype.
This PR fixes it for me: https://github.com/nightscout/AndroidAPS/pull/1119

@Thomas-Wolff would you mind testing if it solves the issue you are experiencing as well? Thanks!

**Comment by Thomas-Wolff** [comment] 2022-01-02 13:48
Hi Adrian, I have already installed the Build 31458fb2b. Today at supper I will test it and send an info.

Thank you very much and have a nice Sunday
Greetings Thomas

**Comment by MilosKozak** [comment] 2022-01-02 13:59
fixed by https://github.com/nightscout/AndroidAPS/commit/faca82f6e853dff5ab27425292dc542691d42245

**Closed by MilosKozak** 2022-01-02 13:59 UTC

**Comment by Thomas-Wolff** [comment] 2022-01-02 14:03
Milos I will update right away and test it at the next bolus.

Thanks for your effort, Greetings Thomas

**Comment by Thomas-Wolff** [comment] 2022-01-02 14:04
Milos I will update right away and test it at the next bolus.

Thanks for your effort, Greetings Thomas
