### ISSUE TITLE
AAPS 2.8. not possible to enter / edit automation name 

### ISSUE THREAD

**Issue by CaroGo** [nightscout/AndroidAPS#173] opened 2021-01-02 17:22 UTC
Version 2.8., poco f1 android 9, DanaRS, 
In this new update it is not possible to name a new automation or edit the name of an already existing automation. You can enter the field, but cannot edit...

**Comment by guydavies** [comment] 2021-01-02 17:33
Did a bunch of new, incomplete questions appear in your objective 3. They
did for me. I haven't tried updating automation rules because I've also not
finished the questions which aren't clear to me still.

**Comment by Rig22** [comment] 2021-01-02 18:32
I can confirm the reported issue @CaroGo.

**Comment by guydavies** [comment] 2021-01-02 19:17
Yep. Me too. I have completed all the new questions and tried exiting and restarting AAPS just to be sure. Like the OP, I could add conditions and actions but the textbox for the title doesn't open a keyboard on screen.

**Comment by MilosKozak** [comment] 2021-01-03 15:02
fixed by https://github.com/nightscout/AndroidAPS/commit/d6f00e5b0d66c6ae12c69b73b400d38d450bf194

**Closed by MilosKozak** 2021-01-03 15:02 UTC
