### ISSUE TITLE
[2.7] no "import settings" possible because of small display size and no scrolling possible

### ISSUE THREAD

**Issue by MarieT1D** [nightscout/AndroidAPS#9] opened 2020-09-27 11:06 UTC
Tested with a "Jelly Pro" from Unihertz (issue maybe also replicable with landscape format for other phones)
If I want to import settings, I only see this and it isn't possible to scroll and click on "ok":
![Screenshot_20200927-125326](https://user-images.githubusercontent.com/37214302/94363312-b9c02e80-00c1-11eb-8af6-c8acd7509e05.png)
after minimizing the size of the file direction:
![Screenshot_20200927-125315](https://user-images.githubusercontent.com/37214302/94363310-b88f0180-00c1-11eb-8860-00488b2c0048.png)
it is still not possible because of the next window (I can't scroll and click on "import")
![Screenshot_20200927-125305](https://user-images.githubusercontent.com/37214302/94363309-b167f380-00c1-11eb-8aec-a8d6e2684e64.png)

Also:
- Objective 3: "Confirm"-Button only accessible on landscape (hidden if you don't now you have to switch to landscape mode)
- Export-Settings

**Comment by osodebailar** [comment] 2020-09-27 12:20
Maybe the same setting as in atom ca solve the problem.
Set the fontsize in settings of jelly to 'small'.
If this does not help, you can do a fast workaround until as solution is implemented:
Search the text 'Du wirst nach dem Master-Passwort gefragt. .......' and delete the second sentence 'Mit diesem werden die importierten Einstellungen entschlüsselt' in strings.xml.
Commit the the file and rebuild master

**Comment by MarieT1D** [comment] 2020-09-27 13:27
Thanks for the hint, but unfortunately it didn't work.
As in the third picture, there are too many listings, so shortening the phrases is not enough and changing the font size doesn't apply for me with this :/

**Comment by osodebailar** [comment] 2020-09-27 13:37
Than the Next workaround , Remove the unneeded Backup Filed from AAps/preferences Directory

**Comment by MarieT1D** [comment] 2020-09-27 13:58
There is only one at AAPS/preferences (which I need to import) or which to you mean?

**Comment by osodebailar** [comment] 2020-09-27 14:04
Ja Marie , alle Backups aus dem Ordner löschen die Du nicht brauchst. dann ist die Liste kurz und es sollte passen

**Comment by MarieT1D** [comment] 2020-09-27 14:09
The list I mean contains the information of the back-up (Name, Date, phone used for the back-up, AAPS Version used for the backup, etc.) (3rd picture)

**Comment by osodebailar** [comment] 2020-09-27 14:20
Ach das meinst Du. Sry. das war für mich keine Liste.
Du kannst alternativ testen den Title 'Einstellungen Importieren' zu kürzen. der Header verbraucht viel Platz. 
Für eine endgültige Lösung muss das Layout überarbeitet werden.

**Comment by MarieT1D** [comment] 2020-09-27 14:25
Already tried that, too, I changed all string variablies I could which have line breaks. The only thing I could still try is changing the size of the header.

**Comment by osodebailar** [comment] 2020-09-27 15:02
Ja da muss man sich Layoutmässig was einfallen lassen.
Wenn es nur um den Import geht , dann öffne die DateI : PrefImportSummaryDialog.kt
und kommentiere die folgenden 2  Zeilen aus 
Zeile 46 
//  val table = (innerLayout.findViewById<View>(R.id.summary_table) as TableLayout)
und Zeile 79 
 // table.addView(rowLayout, idx++)

dann siehst Du keine Zusammnfassung mehr , kannst aber imortieren

**Comment by dlvoy** [comment] 2020-09-27 16:21
Andreas, weil ich ein bisschen verstehe, nicht jede hier ist Deutschsprachige ;)

It is obviously error with summary dialog, which does not allow scrolling on ultra-small screens. I will fix that.
In the meantime - hack mentioned above will allow to import prefs.

**Comment by osodebailar** [comment] 2020-09-27 16:23
Dafuer gibt es Google . Da geht auch English zu deutsch und und umgekehrt . 
Aber ich hatte eh Marie direkt geantwortet .

**Comment by swissalpine** [comment] 2020-09-27 19:56
Yes, I deleted the German language files because the texts are too long and cumbersome for me. But it also seems to me that my font size is smaller, so I have no problems at all on the Atom. Maybe you should check the font size in the Atom settings (Einstellungen > Display > Erweitert> Schriftgröße).
![Screenshot_20200927-214539](https://user-images.githubusercontent.com/12517693/94374326-c49fb100-010b-11eb-8878-c0c081b61846.png)

**Comment by MarieT1D** [comment] 2020-09-27 21:07
> Ja da muss man sich Layoutmässig was einfallen lassen.
> Wenn es nur um den Import geht , dann öffne die DateI : PrefImportSummaryDialog.kt
> und kommentiere die folgenden 2 Zeilen aus
> Zeile 46
> // val table = (innerLayout.findViewById(R.id.summary_table) as TableLayout)
> und Zeile 79
> // table.addView(rowLayout, idx++)
> 
> dann siehst Du keine Zusammnfassung mehr , kannst aber imortieren

Worked, thanks!

**Comment by dlvoy** [comment] 2020-09-29 11:52
After first attempts, seems like AlertDialog.builder inner layout cannot just simple be wrapped with ScrollView. 
Probably whole dialog need refactoring from system-type Dialog to custom Activity, but this will be more complex fix.

**Comment by osodebailar** [comment] 2020-09-29 16:10
@dlvoy i have a solution that work. in the next two days i make a pull request for a review.

**Comment by dlvoy** [comment] 2020-09-29 18:49
Ha! I also worked on it in parallel :D here my attempt:
https://github.com/dlvoy/AndroidAPS/tree/hotfix/import-prefs-layout-uniherz

Do you have device to check it? I only had tested that on Emu.
Please feel free to choose which of those two fixes is better, I can review / emu test yours as well!

**Comment by osodebailar** [comment] 2020-09-29 19:38
I will have a look tomorrow on your solution 
I implemented my solution in my GUI Branch , if you want to have a look.
One of the solution for very small displays is here to set the title as marquee element , and only show the file name , not the path. The path is not interesting for a normal user.
The 3rd solution is in the end when the table in the inner element is shown. I set a nested scroll around .
You can test it here in my “new_gui_to_dev’ Branch 
https://github.com/osodebailar/AndroidAPS

**Comment by MarieT1D** [comment] 2020-09-30 17:43
I will test them, thanks for your work

**Comment by osodebailar** [comment] 2020-09-30 18:23
@MarieT1D you can test my  solution, i have a pull request too of you want.

**Comment by dlvoy** [comment] 2020-10-02 06:28
Fixed by @osodebailar with https://github.com/nightscout/AndroidAPS/pull/15 - so it can be re-tested from `dev` branch.
@MarieT1D  If test on device confirms it is solved - please close issue ;)

**Comment by swissalpine** [comment] 2020-10-02 08:15
I can confirm: The fix works on Unihertz Atom.

**Comment by MarieT1D** [comment] 2020-10-02 12:13
Yesss, it works, thanks so much for you work and sorry for the delay, I will close the issue

**Closed** 2020-10-02 12:13 UTC
