### ISSUE TITLE
[RC1] SMB/Close Loop stops after Calibrations

### ISSUE THREAD

**Issue by parapenT1sta** [nightscout/AndroidAPS#1174] opened 2022-01-14 10:41 UTC
There is a behaviour in AndroidAPS RC1 that I think should be reviewed. Everytime I calibrate using DexcomApp, and the value are very similar, AndroidAPS detects as two readings close to each other and stop the SMB/Close Loop.
In my opinion AndroidAPS should ignore "BG Check" values or the readings adjusted after calibration. This is happening to me quite often. I have to go manually remove the reading in red.
I can be wrong but I feel the issue is related to the BG value adjusted after the calibration.

Calibration was at 8:59 and SMB/Close Loop stop working around 9:30 +/- (as you can check in the graph.

[AndroidAPS_LOG_1642156371451.log.zip](https://github.com/nightscout/AndroidAPS/files/7869732/AndroidAPS_LOG_1642156371451.log.zip)

![Screenshot_20220114-100642](https://user-images.githubusercontent.com/608650/149502592-a79bd301-1d7a-4e71-ac48-ca2f3f55c2ac.png)
![Screenshot_20220114-100647](https://user-images.githubusercontent.com/608650/149502594-f1e2e4cb-8c55-4fb3-b70a-951d3e5ed5e6.png)
![Screenshot_20220114-100655](https://user-images.githubusercontent.com/608650/149502596-59153303-0e14-4354-9427-6a16740e5248.png)
![271848805_1033307574064787_1336009735855990777_n](https://user-images.githubusercontent.com/608650/149502544-38b59648-8c48-4404-8bff-d3bef9fec2b3.jpg)

**Comment by MilosKozak** [comment] 2022-01-14 13:05
time around 8:59 is not in logs

**Comment by parapenT1sta** [comment] 2022-01-14 13:27
I think these two logs cover the time frame of the events.
[AndroidAPS._2022-01-14_00-00-01_.14.zip](https://github.com/nightscout/AndroidAPS/files/7870659/AndroidAPS._2022-01-14_00-00-01_.14.zip)
[AndroidAPS._2022-01-14_00-00-01_.13.zip](https://github.com/nightscout/AndroidAPS/files/7870660/AndroidAPS._2022-01-14_00-00-01_.13.zip)

**Comment by MilosKozak** [comment] 2022-01-14 16:59
are you using G5?

**Comment by MilosKozak** [comment] 2022-01-14 16:59
it looks like a bug in Dexcom app. calibration is sent as BG value too

**Comment by parapenT1sta** [comment] 2022-01-14 17:07
Yes, G5.
As I wrote it seems AndroidAPS marks as "red" reading the value adjusted really after the calibration.

**Comment by parapenT1sta** [comment] 2022-01-14 17:13
@MilosKozak One note, the same problem happens when I initiate a new sensor and enter dual calibrations

**Comment by parapenT1sta** [comment] 2022-01-14 17:16
@MilosKozak One note, the same problem happens when I initiate a new sensor and enter dual calibrations
Same problem with xDrip or BYOD. AndroidAPS assume the dual calibrations as two readings at near time and marked them as red.

**Comment by MilosKozak** [comment] 2022-01-14 17:23
fixed by https://github.com/nightscout/AndroidAPS/commit/0603e741be6c6cd23d2d4b6c84c70de528b63a43
fixed for BOYDA. no way to fix it in xdrip on AAPS side

**Closed by MilosKozak** 2022-01-14 17:23 UTC

**Comment by parapenT1sta** [comment] 2022-01-14 17:48
Thank you @MilosKozak !

Regarding xDrip, what can be the solution? Changes on xDrip itself to avoid broadcast the calibrations?

**Comment by MilosKozak** [comment] 2022-01-15 08:10
i did only workaround as the issue is somewhere in G5 (maybe app only, who knows)
if you see the issue with xDrip too it must be analyzed there
