### ISSUE TITLE
Negative global IOB on graph

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1706] opened 2022-05-07 15:58 UTC
![Screenshot_20220507-175325_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/167262111-6c9bb78b-9be0-4a31-b7d8-2b2101748f48.jpg)

![Screenshot_20220507-175345_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/167262127-237f62a0-b251-4924-bbf0-80eb9c1ab30c.jpg)

Strangely on the graph of global IOB, the line is below zero...

AndroidAPS 3.0.0.2-dev-j 
Build: 16d39421b7-2022.05.07-14:30 

![AndroidAPS_LOG_1651938835801.log.zip](https://github.com/nightscout/AndroidAPS/files/8645517/AndroidAPS_LOG_1651938835801.log.zip)

**Comment by robertrub** [comment] 2022-05-07 16:15
Some time later... The upper part of globsl IOB has been colored but the line is still below zero...

![Screenshot_20220507-181409_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/167262835-7a38349e-13b3-426d-972f-3a8b84a5baba.jpg)

**Comment by robertrub** [comment] 2022-05-07 16:42
And a bit later...

![Screenshot_20220507-183823_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/167263747-fa2f7502-2149-4542-9f98-5ac0f22292c9.jpg)

**Comment by ArthurusDent** [comment] 2022-05-07 18:30
Duplicate of #1609 and #1597. 

Maybe sum up your but report into one post and add to #1597?

**Closed** 2022-05-10 18:40 UTC
