### ISSUE TITLE
[AAPS 3.0.0] Bolus Wizard calculation Settings page BG value shown as x/18 mmol/l.

### ISSUE THREAD

**Issue by reijoahola-nightscout** [nightscout/AndroidAPS#1298] opened 2022-02-10 12:25 UTC
Using Bolus Wizard for bolus calcultation and the results are shown in Treatments tab. Openig the results from green "Calc" link that shows the calculation settings. The first line has BG value left to ISF value but BG is not shown correctly but as a value x/18 mmol/l .

**Comment by Philoul** [comment] 2022-02-10 18:47
Can you please send a screenshot and associated log please.
My setting is with mg/dl and I cannot reproduce your issue.

![Screenshot_20220210-193951_AndroidAPS.jpg](https://user-images.githubusercontent.com/52934600/153475183-c0699188-a446-4abb-bcb9-b210934a75d2.jpg)

**Comment by reijoahola-nightscout** [comment] 2022-02-10 19:10
No mg/dl in settings. I use mmol/l in all places. The place for wrong number is where you have a number 167. May be the problem does not exist when the setting mg/dl is used. It looks like it does not cause any problems in the opwereation of AAPS, it is just a display problem and can cause confusion for the user.

**Comment by reijoahola-nightscout** [comment] 2022-02-10 19:12
I try later generate the log files and screenshots.

**Comment by reijoahola-nightscout** [comment] 2022-02-11 11:05
It is OK now.

**Comment by Philoul** [comment] 2022-02-11 13:40
Thanks, 
fixed by https://github.com/nightscout/AndroidAPS/pull/1301/commits/c5d13147f3c8aa91b8d3964878b2cf1b7f21af4d

**Closed** 2022-03-13 07:21 UTC
