### ISSUE TITLE
[DEV] Error "Profile sensitivity value" is out of hard limits when enabling "Dynamic sensitivity"

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3226] opened 2024-02-18 15:28 UTC
AAPS 3.3.0-dev-a
Build: 9c327b4e4c-2024.02.17
Logs: [AndroidAPS_LOG_1708209853078.log.zip](https://github.com/nightscout/AndroidAPS/files/14323055/AndroidAPS_LOG_1708209853078.log.zip)

Step-by-step to reproduce:
1. Start with "Dynamic sensitivity" disabled in SMB plugin. Run a loop or two.
2. Enable "Dynamic sensitivity". Execute loop, either on next loop run or manually via Loop plugin. Error should pop up.
3. After error, when next BG arrive then automatic looprun returns no error.

Can't see any issues with profile values.

Screenshots:
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/31cb6b52-15dc-4a5d-ba86-1361f8017cef)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/a9bf3600-ef1b-492e-9bf5-8f894c87cdc3)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/ceda0955-5287-4a8f-a7e0-acfcae751dd5)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/ec1a2cf5-c3a4-44d2-96ca-be8ac426eef5)

**Comment by Heiner1** [comment] 2024-02-18 15:49
Same to me. Did you also switch from another AAPS-development-idea to the original dev-version?

**Comment by Heiner1** [comment] 2024-02-18 15:57
I'll try to reproduce it the same way.

**Comment by Heiner1** [comment] 2024-02-18 16:55
You're right, error message is reproducable, exactly the same behaviour. For me the difference is now: DynISF Loop is running again. Bevor I got more error messages and no falling back to normal SMB mode - loop had been deactivated. So I think it has something to do with database? 
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/14323536/AndroidAPS.log)

**Comment by ga-zelle** [comment] 2024-02-18 17:06
I came across that message a lot in the recent days. I was focused on some other topic and did not drill down to base reason. However, my impression was that the message text is very misleading because it seems related to variable_sens as used in DynamicISF and has nothing to do with the pump profile sensitivity. If not yet calculated then variabale_sens may get assigned 0.0 or 1.0 which triggers the message. If assigning 100.0 when not used or not yet calculated then there was no message.

**Comment by vanelsberg** [comment] 2024-02-20 10:33
> Step-by-step to reproduce:

Confirming,
Seeing the same on current dev#9c327b4e

**Comment by lostboy86** [comment] 2024-02-20 17:08
it's the same issue of mine : 

https://github.com/nightscout/AndroidAPS/issues/3192

**Comment by robinsondan87** [comment] 2024-06-17 19:36
Is there a way to work around this or stop the error from happening?

**Comment by vanelsberg** [comment] 2024-06-18 13:31
> Step-by-step to reproduce

Confirming. Have also been seeing this some time ago. Looks like your repro...

**Comment by MilosKozak** [comment] 2024-11-13 13:13
still there?

**Comment by olorinmaia** [comment] 2024-11-13 16:30
Yes. Do you need fresh logs?

**Comment by olorinmaia** [comment] 2024-11-16 18:14
Sharing logs and a screenshot. Same steps to reproduce as in original description of issue.

[AndroidAPS_LOG_1731769511492.log.zip](https://github.com/user-attachments/files/17787544/AndroidAPS_LOG_1731769511492.log.zip)
![image](https://github.com/user-attachments/assets/6cf317bf-f052-4903-b5f0-0aa6d78fafe6)

**Comment by MilosKozak** [comment] 2024-11-27 13:27
fixed in https://github.com/nightscout/AndroidAPS/commit/80fd9e4d8be5f72858954b491675bc92f14a07e7

**Closed by MilosKozak** 2024-11-27 13:27 UTC
